//PACKAGE BR.COM.PROJETOINTEGRADO;
//
//IMPORT ORG.JUNIT.JUPITER.API.TEST;
//IMPORT ORG.SPRINGFRAMEWORK.BOOT.TEST.CONTEXT.SPRINGBOOTTEST;
//
//@SPRINGBOOTTEST
//CLASS SWAGGERAPPLICATIONTESTS {
//
//	@TEST
//	VOID CONTEXTLOADS() {
//	}
//
//}